import type { Transfer } from "./types";

// Demo verisi — gerçek bir API'ye (ör. /api/transfers) kolayca taşınabilir.
// Antigravity'deki kaynak yapıştırıldığında bu liste onunla değiştirilebilir.
export const TRANSFERS: Transfer[] = [
  {
    id: "t1",
    player: "Mauro Icardi",
    age: 31,
    position: "FWD",
    from: { name: "Galatasaray", league: "Süper Lig" },
    to: { name: "Galatasaray", league: "Süper Lig" },
    fee: 10,
    reliability: 92,
    status: "official",
    source: "Galatasaray SK",
    updatedAt: "2026-06-15T09:30:00Z",
  },
  {
    id: "t2",
    player: "Victor Osimhen",
    age: 27,
    position: "FWD",
    from: { name: "Napoli", league: "Serie A" },
    to: { name: "Galatasaray", league: "Süper Lig" },
    fee: 75,
    reliability: 68,
    status: "talks",
    source: "Fabrizio Romano",
    updatedAt: "2026-06-15T11:10:00Z",
  },
  {
    id: "t3",
    player: "Edon Zhegrova",
    age: 26,
    position: "FWD",
    from: { name: "Lille", league: "Ligue 1" },
    to: { name: "Juventus", league: "Serie A" },
    fee: 18,
    reliability: 85,
    status: "agreed",
    source: "Di Marzio",
    updatedAt: "2026-06-14T18:45:00Z",
  },
  {
    id: "t4",
    player: "Florian Wirtz",
    age: 23,
    position: "MID",
    from: { name: "Bayer Leverkusen", league: "Bundesliga" },
    to: { name: "Manchester City", league: "Premier League" },
    fee: 130,
    reliability: 55,
    status: "rumor",
    source: "Sky Germany",
    updatedAt: "2026-06-15T07:00:00Z",
  },
  {
    id: "t5",
    player: "Alphonso Davies",
    age: 25,
    position: "DEF",
    from: { name: "Bayern Münih", league: "Bundesliga" },
    to: { name: "Real Madrid", league: "LaLiga" },
    fee: 0,
    reliability: 40,
    status: "rumor",
    source: "Marca",
    updatedAt: "2026-06-13T14:20:00Z",
  },
  {
    id: "t6",
    player: "Bruno Guimarães",
    age: 28,
    position: "MID",
    from: { name: "Newcastle", league: "Premier League" },
    to: { name: "FC Barcelona", league: "LaLiga" },
    fee: 90,
    reliability: 35,
    status: "rumor",
    source: "Mundo Deportivo",
    updatedAt: "2026-06-12T20:00:00Z",
  },
  {
    id: "t7",
    player: "Hakan Çalhanoğlu",
    age: 32,
    position: "MID",
    from: { name: "Inter", league: "Serie A" },
    to: { name: "Fenerbahçe", league: "Süper Lig" },
    fee: 22,
    reliability: 60,
    status: "talks",
    source: "Gianluca Di Marzio",
    updatedAt: "2026-06-15T10:05:00Z",
  },
  {
    id: "t8",
    player: "Nico Williams",
    age: 23,
    position: "FWD",
    from: { name: "Athletic Bilbao", league: "LaLiga" },
    to: { name: "FC Barcelona", league: "LaLiga" },
    fee: 58,
    reliability: 78,
    status: "agreed",
    source: "Fabrizio Romano",
    updatedAt: "2026-06-14T22:30:00Z",
  },
  {
    id: "t9",
    player: "Marcus Rashford",
    age: 28,
    position: "FWD",
    from: { name: "Manchester United", league: "Premier League" },
    to: { name: "Aston Villa", league: "Premier League" },
    fee: 40,
    reliability: 50,
    status: "talks",
    source: "The Athletic",
    updatedAt: "2026-06-11T16:40:00Z",
  },
  {
    id: "t10",
    player: "Goncalo Ramos",
    age: 24,
    position: "FWD",
    from: { name: "PSG", league: "Ligue 1" },
    to: { name: "Newcastle", league: "Premier League" },
    fee: 45,
    reliability: 20,
    status: "collapsed",
    source: "L'Équipe",
    updatedAt: "2026-06-10T12:00:00Z",
  },
  {
    id: "t11",
    player: "Sandro Tonali",
    age: 26,
    position: "MID",
    from: { name: "Newcastle", league: "Premier League" },
    to: { name: "AC Milan", league: "Serie A" },
    fee: 60,
    reliability: 30,
    status: "rumor",
    source: "Calciomercato",
    updatedAt: "2026-06-09T19:15:00Z",
  },
  {
    id: "t12",
    player: "Youssef En-Nesyri",
    age: 29,
    position: "FWD",
    from: { name: "Fenerbahçe", league: "Süper Lig" },
    to: { name: "West Ham", league: "Premier League" },
    fee: 35,
    reliability: 47,
    status: "talks",
    source: "Yağız Sabuncuoğlu",
    updatedAt: "2026-06-15T08:20:00Z",
  },
];
